Implemented Delete Selected button functionality
Revolutionary-Games/Thrive pull request #1566
Opened 2020-08-22 23:15 UTC by DTanxxx

Delete Selected button functionality implemented, as well as a confirm dialog. Also added a call to UpdateSelectedCount in _Process after getSaveCountTask is completed, in SaveManagerGUI, so that the selected count is shown and updated correctly.

closes #1416
closes #1562
closes #1458

2020-08-24 15:41 UTC, hhyyrylainen requested changes
Fine, I'll do it myself (and review this).
Looks like everything else is working except when I selected two saves and hit the trashcan button on one of those the selected number of saves text wasn't updated:
![Kuvakaappaus - 2020-08-24 18-39-49](https://user-images.githubusercontent.com/3796411/91065629-6594db00-e639-11ea-9603-2ed575cb1d8a.png)

2020-08-24 22:03 UTC, DTanxxx commented
If the trashcan button is pressed the SaveList class will handle the deletion. Since SaveList does not have a reference to the selectedItemCount label in SaveManagerGUI, it cannot update the label right after deletion and requires the Refresh button to be pressed. The way the selectedItemCount label is updated is very similar to totalSaveCount and totalSaveSize labels, where Refresh button needs to be pressed in order to update. However if updating selectedItemCount straight away is the desired effect then I can make `UpdateSelectedCount` method in SaveManagerGUI class a public static method so that I can reference it in SaveList class in _Process

2020-08-25 05:25 UTC, hhyyrylainen commented
If the top level component needs to react to an event from a child component, the child component should define a new signal.
In fact the list item already communicates the deletion through a signal:
https://github.com/Revolutionary-Games/Thrive/blob/7a2889789a89aafbb8ee700046f4271bf58aaae5/src/saving/SaveListItem.cs#L67
Though it probably doesn't reach the save manager, so the list should also define such a signal, like OnItemsChanged so that the save manager can listen for that.

2020-08-25 15:54 UTC, hhyyrylainen requested changes

2020-08-25 15:54 UTC, hhyyrylainen commented on src/saving/SaveList.cs
> -        Refresh();
Removing this refresh breaks refresh in the "Load Game" from the pause menu.

2020-08-25 15:54 UTC, hhyyrylainen commented on src/saving/SaveManagerGUI.cs
> +        UpdateSelectedCount();
I would like these two lines to be above the `refreshing = false` line as conceptually I imagine that to be like the end of this method, marking things as done.

2020-08-25 15:54 UTC, hhyyrylainen commented on src/saving/SaveManagerGUI.cs
> +        Selected.ForEach(item => SaveHelper.DeleteSave(item.SaveName));
I'd add a blank line before this line to give the code more room to breathe.

2020-08-26 10:12 UTC, hhyyrylainen approved these changes
I didn't find any further problems.

2020-08-26 10:12 UTC, merged