Options fixes.
Revolutionary-Games/Thrive pull request #1595
Opened 2020-09-10 10:52 UTC by Satharis

Added a new WindowDialog control that allows continue/save, continue/discard and cancel when closing the options menu, also fixed the other bug.

Fixes #1592 
Fixes #1593

2020-09-10 14:26 UTC, Kasterisk approved these changes
Seems good, did a quick test and it also works nicely

2020-09-10 14:32 UTC, hhyyrylainen requested changes
I noticed that when the chromatic aberration box is checked, it doesn't react to mouse hover the same way for example the vsync option does when it is selected. When chromatic aberration isn't selected it reacts to mouse hover. Any idea what's up with that?

2020-09-10 14:32 UTC, hhyyrylainen commented on src/general/OptionsMenu.cs
> +            GD.PrintErr("Failed to save new options menu settings.");
It would be nice to show this error in a popup box so the user isn't confused in the unlikely scenario that the saving fails.

2020-09-10 14:32 UTC, hhyyrylainen commented on src/general/OptionsMenu.tscn
> +[sub_resource type="StyleBoxEmpty" id=9]
It seems that whenever I reopen this in godot editor (after resetting changes) godot absolutely wants to reorder things.
So could you close your godot editor, and reopen it, it should do some reordering on this file.

2020-09-10 18:39 UTC, Satharis commented
Added the error popup dialog and fixed that issue with mouseover, it didn't have a style set that the other checkboxes did for the case of it being pressed.

2020-09-10 18:44 UTC, hhyyrylainen commented
Could you move the checkbox stuff to the thrive main theme file (src/gui_common/thrive_theme.tres)? So that it doesn't need to be manually added for all checkboxes.

2020-09-10 19:38 UTC, Satharis commented
I checked and the style is already set in the theme actually, seems to be an engine bug.
https://github.com/godotengine/godot/issues/34727
Doesn't actually apply the style unless custom override is set on the control.

2020-09-10 19:42 UTC, hhyyrylainen commented
Interesting. Hopefully that fix will get merged earlier rather than later, I'll open an issue to remember to clean things up.
https://github.com/Revolutionary-Games/Thrive/issues/1599

2020-09-11 07:49 UTC, hhyyrylainen approved these changes
Everything looks to work fine now. Didn't see any further issues in the code either.

2020-09-11 07:49 UTC, merged