Added numbers to show ATP balance
Revolutionary-Games/Thrive pull request #1607
Opened 2020-09-13 08:21 UTC by DTanxxx

Added energyBalance.FinalBalance to the label's text.

2020-09-13 08:25 UTC, hhyyrylainen requested changes
This is not what I imagined the bars should do.
Instead both the production and consumption bar should show a number for their details.
Just showing the total balance doesn't solve the issue "Add numbers **back** to the ATP --" which means that before both the bars showed their total value, and they don't anymore and it'd be nice to have that back.

2020-09-13 08:41 UTC, DTanxxx commented
Oh right, is it fine if I add labels to both bars showing the totals (since you said before that it would look cluttered)?

2020-09-13 08:53 UTC, hhyyrylainen commented
That's what I want. I meant that as the bars (there are 2) have sub-bars (these are the ones with icons and different colours), having numbers on those sub-bars would make things cluttered. I do want both of the bars to have their totals on them.

2020-09-14 01:25 UTC, DTanxxx commented
I added labels underneath the two bars so it's easier to read.

2020-09-14 05:52 UTC, hhyyrylainen requested changes
The numbers should be to the right of the bars in order to not need the explanation text that takes up extra space.

2020-09-15 09:27 UTC, hhyyrylainen commented on src/microbe_stage/editor/MicrobeEditorGUI.cs
> +        atpProductionLabel.AddColorOverride("font_color", new Color(1.0f, 1.0f, 1.0f));
Is this needed? Isn't this the default colour?

2020-09-15 09:28 UTC, hhyyrylainen commented
There isn't much code to review, so I requested @Kasterisk reviews the GUI side of things.

2020-09-15 10:37 UTC, Kasterisk requested changes
For the labels, the horizontal `fill` size flag also needs to be enabled so the text's horizontal alignment can take effect.

2020-09-15 10:37 UTC, Kasterisk commented on src/microbe_stage/editor/MicrobeEditorGUI.cs
> +        atpProductionLabel.Text = $"{energyBalance.TotalProduction}";
Shoud be formatted to as how it was before: `string.Format(CultureInfo.CurrentCulture, "{0:F1}", energyBalance.TotalProduction);` (and the same for `TotalConsumption`) to limit the decimals to only one digit

2020-09-16 11:01 UTC, hhyyrylainen requested changes

2020-09-16 11:01 UTC, hhyyrylainen commented on project.godot
> +"events": [ Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"alt":false,"shift":false,"control":true,"meta":true,"command":true,"pressed":false,"scancode":90,"unico
These are probably once again unintended keybinding changes.

2020-09-16 12:09 UTC, Kasterisk approved these changes
Other than hhyyrylainen mentioned above, looks good

2020-09-17 06:16 UTC, hhyyrylainen approved these changes

2020-09-17 06:16 UTC, merged

2020-09-17 07:37 UTC, hhyyrylainen commented
Hey @DTanxxx you have done quite a few PRs now. Have you considered applying to the team https://revolutionarygamesstudio.com/application/ ? You can use your PRs as work samples to get accepted.