Balancetweak
Revolutionary-Games/Thrive pull request #1665
Opened 2020-09-30 02:50 UTC by buckly90

Made some small tweaks to hopefully make the game more enjoyable.

- Limited all patch lighting to a maximum of 100% No more 150% or above.
- Buffed photosynthesis a little to make up for the lower limits of light.
- Rearranged membrane stats in an attempt to make each type more unique and viable.
- Buffed respiration parts. You can now support a flagellum with as little as two metabolosomes. (Your still gonna need alot if you want to be complex.)

These changes will be revisited once the spawn system is finalized and I am able to freely tweak compound rates. For now, the changes are aimed to hopefully make the game more enjoyable in it's current state.

2020-09-30 02:52 UTC, buckly90 commented
I'm not currently sure where the code for the membrane tooltips resides, and I need to change that so the editor displays the appropriate stats for membranes.

2020-09-30 06:22 UTC, hhyyrylainen requested changes
I think the tooltips might be in ToolTipManager.tscn, though @Kasterisk probably knows better

2020-09-30 06:22 UTC, hhyyrylainen commented on simulation_parameters/microbe_stage/biomes.json
> -                            "scenePath": "res://src/microbe_stage/ToxinCloud.tscn"
This file looks like all the changes are backwards, this reverts the change to moving to using particles for the toxins.

2020-09-30 08:01 UTC, Kasterisk commented
Yeah all the custom tooltips are currently in ToolTipManager.tscn. The modifier values are hardcoded on the tooltip gui so you need to tweak the the gui labels text to change them.

2020-09-30 16:34 UTC, buckly90 commented
Tooltips have been changed, I went ahead and converted the remaining decimal values to percentage as well, I also fixed the issue with my commit reverting the changes to toxins.

2020-09-30 17:56 UTC, hhyyrylainen approved these changes
Looks like there are no longer any problems with unintended changes being included.
@Kasterisk could you check the GUI changes?
Other than that we might want to hear balance feedback from other devs.

2020-10-01 05:46 UTC, Kasterisk approved these changes
Looks good

2020-10-02 14:30 UTC, hhyyrylainen commented
I'll merge this to prepare for tomorrow's release candidate.

2020-10-02 14:49 UTC, merged