Added setting to change username
Revolutionary-Games/Thrive pull request #1775
Opened 2020-10-28 00:18 UTC by icedjuro

Closes #1341

2020-10-28 16:58 UTC, Kasterisk approved these changes
Tested this earlier and I think it works pretty good

2020-10-28 17:14 UTC, hhyyrylainen commented on src/engine/Settings.cs
> +    public SettingValue<string> CustomUsername { get; set; } = new SettingValue<string>(string.Empty);
Where does the crash happen if this is null? I think it might be a good idea to try to fix that.

2020-10-29 11:56 UTC, hhyyrylainen requested changes
Found a problem: if custom username is enabled but nothing is put in the field, the username is left blank.

2020-10-29 11:56 UTC, hhyyrylainen commented on src/saving/SaveInformation.cs
> +        Settings.Instance.CustomUsernameEnabled ?
I think this should also check that CustomUsername is not null, if it is then Environment.UserName should be used.

2020-10-29 15:25 UTC, hhyyrylainen requested changes

2020-10-29 15:25 UTC, hhyyrylainen commented on src/engine/Settings.cs
> +    public string CustomUsernameValue =>
This needs to be JsonIgnore, also a better name would be `ActiveUsername` to indicate that this isn't actually just the value of custom username.

2020-10-29 15:56 UTC, hhyyrylainen approved these changes

2020-10-29 15:56 UTC, merged