Auto Evo Config is stored in JSON
Revolutionary-Games/Thrive pull request #1916
Opened 2020-12-12 21:48 UTC by icedjuro

Closes #1020

2020-12-12 22:05 UTC, hhyyrylainen requested changes

2020-12-12 22:05 UTC, hhyyrylainen commented on src/auto-evo/AutoEvoConfiguration.cs
> +    public bool ALLOW_NO_MIGRATION;
These should be named according to the normal C# field. Also converting these to properties with private set and the jsonproperty attribute would protect against someone trying to modify these during runtime.

2020-12-12 22:05 UTC, hhyyrylainen commented on src/auto-evo/AutoEvoConfiguration.cs
> +            throw new InvalidRegistryDataException("NameGenerator", GetType().Name,
`NameGenerator` doesn't belong here

2020-12-12 22:05 UTC, hhyyrylainen commented on simulation_parameters/common/autoevo_parameters.json
> +    "ALLOW_NO_MIGRATION": true
The new naming needs to also apply here

2020-12-14 12:39 UTC, hhyyrylainen requested changes

2020-12-14 12:39 UTC, hhyyrylainen commented on src/auto-evo/AutoEvoConfiguration.cs
> +    /// <value>The name of the internal.</value>
What even is this comment. Unused is fine to keep but it should be intended 2 spaces.

2020-12-14 16:33 UTC, hhyyrylainen approved these changes

2020-12-14 16:33 UTC, hhyyrylainen commented
You probably need to add a BOM now to that one new file you added for CI to accept it.

2020-12-15 08:17 UTC, icedjuro commented
@hhyyrylainen how do i do that?

2020-12-15 08:20 UTC, hhyyrylainen commented
Google "YOUREDITOR UTF8 BOM" to see how you can save files with BOM.

2020-12-15 08:34 UTC, merged