Apply Language Settings when return from editor #1885
Revolutionary-Games/Thrive pull request #1923
Opened 2020-12-14 12:11 UTC by Sourciluss667

This fix issue #1885
Apply language settings in OnReturnFromEditor() in MicrobeStage.cs

2020-12-14 12:31 UTC, hhyyrylainen requested changes

2020-12-14 12:31 UTC, hhyyrylainen commented on src/microbe_stage/MicrobeStage.cs
> +        // Apply language settings (to fix bug, see #1885)
This comment should have the full explanation that due to the stage scene tree being unattached during editor, if language was changed while in the editor, it doesn't properly propagate. So language is reapplied here to make sure that the stage doesn't continue to use the wrong language.

2020-12-14 14:07 UTC, hhyyrylainen approved these changes

2020-12-14 14:08 UTC, hhyyrylainen commented
CI is failing due to trailing whitespace.
If someone can verify that this fixes the issue #1885 this is good to merge (once CI issue is fixed).

2020-12-14 14:09 UTC, Kasterisk approved these changes

2020-12-14 17:50 UTC, FuJa0815 approved these changes

2020-12-15 09:42 UTC, icedjuro approved these changes

2020-12-15 15:00 UTC, merged