1894 - untranslatable strings
Revolutionary-Games/Thrive pull request #2061
Opened 2021-01-26 02:17 UTC by zackdrake

fixes #1894

2021-01-26 09:55 UTC, Kasterisk requested changes

2021-01-26 09:55 UTC, Kasterisk commented on src/auto-evo/RunResults.cs
> +                    builder.Append(TranslationServer.Translate("EXTINCT"));
```suggestion
                    builder.Append(TranslationServer.Translate("WENT_EXTINCT_IN"));
```

2021-01-26 09:55 UTC, Kasterisk commented on src/auto-evo/RunResults.cs
> +                    builder.Append(TranslationServer.Translate("WENT_EXTINCT"));
```suggestion
                    builder.Append(TranslationServer.Translate("WENT_EXTINCT_FROM_PLANET"));
```

2021-01-26 10:26 UTC, hhyyrylainen requested changes

2021-01-26 10:26 UTC, hhyyrylainen commented on src/auto-evo/RunResults.cs
>                      builder.Append(PatchString(patch));
For some languages it is not natural to have this say "went extinct in x" so this should instead use a translation string with placeholder in it that uses PatchString(path) as the parameter to format.

2021-01-26 10:26 UTC, hhyyrylainen commented on src/auto-evo/RunResults.cs
>                      builder.Append("  ");
This should have one space added, right to reflect that " went extinct in" started with a space.

2021-04-01 11:43 UTC, Kasterisk commented
Updated the PR, I think this is fine to merge now.

2021-04-01 11:45 UTC, Kasterisk approved these changes

2021-04-01 11:48 UTC, hhyyrylainen commented
I'll re-check this.

2021-04-01 11:49 UTC, hhyyrylainen approved these changes

2021-04-01 11:50 UTC, merged

2021-09-23 14:12 UTC, hhyyrylainen commented
@zackdrake we are in the process of getting a CLA in-place for Thrive in order to make it possible to have Thrive on Steam. Could you maybe sign the CLA? You can do that here: https://dev.revolutionarygamesstudio.com/cla