Make Converter classes also catch ArgumentNullException
Revolutionary-Games/Thrive pull request #2064
Opened 2021-01-26 07:05 UTC by Apsum

#1863

2021-01-26 09:56 UTC, Kasterisk requested changes
I'm assuming this would work as intended. One code formatting issue:

2021-01-26 09:56 UTC, Kasterisk commented on src/saving/serializers/ThriveJsonConverter.cs
> +        if ( item == null)
There's a whitespace in front of the first bracket.

2021-01-26 12:35 UTC, hhyyrylainen requested changes

2021-01-26 12:35 UTC, hhyyrylainen commented on src/saving/serializers/ThriveJsonConverter.cs
> +            throw new ArgumentNullException($" Non existing key from JObject: {item} ");
Umm, the issue is about *catching* in the various converters like GodotColourConverter, GodotBasisConverter etc. and not about throwing here. And btw `item` is already used on line 670 so this check against null here is not very useful.

2021-07-10 09:27 UTC, hhyyrylainen commented
@FuJa0815 did you revert all changes done by @Apsum ? If so, I think you should make a new PR instead...

2021-07-16 11:12 UTC, closed without merging