Fixed 4x symmetry hex rotations
Revolutionary-Games/Thrive pull request #2161
Opened 2021-03-30 14:45 UTC by Kasterisk

Now rotates at the correct angles:
![rotation](https://user-images.githubusercontent.com/54026083/113008168-01269500-91a1-11eb-8382-3d617c4ca3e0.gif)

Fixes #1153

2021-03-30 16:49 UTC, FuJa0815 requested changes

2021-03-30 16:49 UTC, FuJa0815 commented on src/microbe_stage/editor/MicrobeEditor.tscn
> +margin_bottom = 662.0
I'd revert this file:
```suggestion
margin_left = 160.0
margin_top = 183.0
margin_right = 463.0
margin_bottom = 658.0
```

2021-03-31 21:35 UTC, buckly90 commented
After testing the most recent commit, the 4-way symmetry now works exactly as intended. Great work Kasterisk!

2021-04-01 06:29 UTC, hhyyrylainen approved these changes

2021-04-01 06:38 UTC, merged