Fixed Population Hud Wrapping
Revolutionary-Games/Thrive pull request #2166
Opened 2021-03-31 21:45 UTC by Pickles4Life

When appropriate population is displayed in the thousands and millions. Fixes #2154.

2021-04-01 09:43 UTC, Kasterisk requested changes

2021-04-01 09:43 UTC, Kasterisk commented on src/microbe_stage/MicrobeHUD.cs
> +        if (playerPopulation < 1000)
There's already a static helper method for the formatting: `StringUtils.FormatNumber`. I'd use it here since it also handles translations.

2021-04-02 10:12 UTC, Kasterisk approved these changes
Looks good, thanks for your contribution!

2021-04-02 10:19 UTC, merged

2021-09-23 14:18 UTC, hhyyrylainen commented
@Pickles4Life we are in the process of getting a CLA in-place for Thrive in order to make it possible to have Thrive on Steam. Could you maybe sign the CLA? You can do that here: https://dev.revolutionarygamesstudio.com/cla