Issue_2195_disabled undo button when starting organelle moving
Revolutionary-Games/Thrive pull request #2229
Opened 2021-05-15 13:33 UTC by Snacklemore

Hello,
Pretty easy fix, just disabled the undo Button when moving started. I thought I would have to  nable it afterwards when placing,  
but the update when placing seems to do it already.

2021-05-15 14:53 UTC, Kasterisk requested changes
The undo/redo could still be accessed via shortcut keys. I think it's good if they're also disabled by adding guards in `Undo()` and `Redo()` method in the editor class that checks whether `MovingOrganelle` is null, and returns if it's not.

2021-05-15 14:53 UTC, Kasterisk commented on src/microbe_stage/editor/MicrobeEditor.cs
> +        gui.SetUndoButtonStatus(false);
The redo button need to be disabled here also.

2021-05-15 17:54 UTC, hhyyrylainen requested changes
Doesn't work correctly with saving:
- Start an organelle move
- Save and then immediately load
- Notice that the undo button is enabled

2021-07-10 12:42 UTC, Kasterisk approved these changes
Improved the functionality and made this work with saving.

2021-07-14 14:02 UTC, hhyyrylainen commented
Looking at your changes @Kasterisk it almost looks like you rewrote the entire PR... If you did, could you make a separate PR just from your commit?

2021-07-14 15:17 UTC, closed without merging