Added info to Graphics Tab
Revolutionary-Games/Thrive pull request #2380
Opened 2021-06-27 22:35 UTC by nle244

**Brief Description of What This PR Does**

Graphics Tab additions:
-Display current GPU
-Display Renderer
-Display Video Memory usage

**Related Issues**

Fixes issue #2373 

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [x ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

2021-06-28 07:47 UTC, Kasterisk requested changes
There are multiple failing checks, so those needs to be addressed first. Here is one of the diff:
```diff
index c1b4b0da..a51581d4 100644
--- a/src/general/OptionsMenu.cs
+++ b/src/general/OptionsMenu.cs
@@ -357,7 +357,6 @@ public class OptionsMenu : Control
         // We're only utilizing the AcceptDialog's auto resize functionality,
         // so hide the default Ok button since it's not needed
         backConfirmationBox.GetOk().Hide();
-
     }
 
     public override void _Notification(int what)
@@ -1162,6 +1161,6 @@ public class OptionsMenu : Control
 
         currentGpu.Text = VisualServer.GetVideoAdapterName();
         displayDriver.Text = OS.GetCurrentVideoDriver().ToString();
-        videoMem.Text = videoMemUsed.ToString() + " MB";
+        videoMem.Text = videoMemUsed + " MB";
     }
 }
```
Apart from that, some comments and some things that could be improved below:

2021-06-28 07:47 UTC, Kasterisk commented on src/general/OptionsMenu.cs
> +    public NodePath VideoMemPath;
According to the style guide abbreviations should avoided so this variable should preferably be named `VideoMemoryPath`. There also other places that needs the adjustment where shortening is used.

2021-06-28 07:47 UTC, Kasterisk commented on src/general/OptionsMenu.cs
> +        videoMem.Text = videoMemUsed.ToString() + " MB";
The used unit of measurement is mebibyte so instead of `MB` it should be `MiB`.

2021-06-28 07:47 UTC, Kasterisk commented on src/general/OptionsMenu.cs
> +    public NodePath DisplayDriverPath;
This should be named `DisplayRendererPath`, needs to be corrected down the line too for occurrences of "drivers".

2021-06-28 07:47 UTC, Kasterisk commented on src/general/OptionsMenu.tscn
> +text = "GPU:"
These texts should be localized, see: [working_with_translations.md](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/working_with_translations.md#working-with-translation).

2021-06-28 07:47 UTC, Kasterisk commented on src/general/OptionsMenu.tscn
> +text = "GPU Info"
In addition to the translation documentation linked which also this covered: for texts that will be overridden in the code, `PLACEHOLDER` should be added to the editor description so this placeholder text would not be fetched by the translation system.

2021-06-28 07:47 UTC, Kasterisk commented on src/general/OptionsMenu.tscn
> +[connection signal="focus_entered" from="CenterContainer/VBoxContainer/PanelContainer/MarginContainer/Graphics" to="." method="_on_Graphics_focus_entered"]
What does this signal connection do?

2021-06-28 07:47 UTC, Kasterisk commented on src/gui_common/thrive_theme.tres
> -[ext_resource path="res://assets/textures/gui/bevel/hSeparatorCentered.png" type="Texture" id=4]
Changes to this file should be reverted as if this line is removed (and one other some lines below this) could likely break the thrive themed styling.

2021-06-28 07:47 UTC, Kasterisk commented on assets/models/organelles/Flagellum.glb.import
> +nodes/use_legacy_names=true
I'm guessing this change doesn't break anything but in my experience it's good to avoid unrelated changes in a PR as much as possible.

2021-09-10 16:29 UTC, hhyyrylainen commented
@nle244 will you be finishing this PR sometime in the future? If you don't plan on completing this, could you at least sign our CLA (https://dev.revolutionarygamesstudio.com/cla) so that someone else can finish this PR?

2021-12-10 03:39 UTC, Kasterisk commented
I think this can now be closed given this PR has been stale for a long time and https://github.com/Revolutionary-Games/Thrive/issues/2373#issuecomment-973798853.

2021-12-10 03:39 UTC, closed without merging