Added equality checks to ActiveMenu
Revolutionary-Games/Thrive pull request #2399
Opened 2021-07-11 09:25 UTC by FuJa0815

**Brief Description of What This PR Does**

This PR stops the user from repeadatly pressing F1 to randomize the easter egg message.

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

2021-07-11 10:54 UTC, Kasterisk commented
Personally I kind of like being able to randomize the easter eggs on demand but that would defeat their purpose I guess :P.

Anyways a better way for this is to have an enum specifying the menus similarly to how the tabs in MicrobeEditorGUI are handled. So SetActiveMenu method could be left as is and the enum could be used to check what's the current opened menu. See [MicrobeEditorGUI.cs#L1474](https://github.com/Revolutionary-Games/Thrive/blob/master/src/microbe_stage/editor/MicrobeEditorGUI.cs#L1474) and [MicrobeEditorGUI.cs#L409](https://github.com/Revolutionary-Games/Thrive/blob/master/src/microbe_stage/editor/MicrobeEditorGUI.cs#L409)

2021-07-11 11:36 UTC, FuJa0815 commented
I was thinking about this too. I was wondering why this was implemented with strings and not enums. I'll change this to an enum-based approach.

2021-07-11 11:43 UTC, Kasterisk commented
The PauseMenu class predates the enum based tab/page handling in the codebase so it just needs some a bit of refactoring.

2021-07-14 13:59 UTC, hhyyrylainen requested changes
Other than that one naming thing this looks good.

2021-07-14 13:59 UTC, hhyyrylainen commented on src/general/PauseMenu.cs
> +    private enum MenuEnum
```suggestion
    private enum ActiveMenuType
```
I don't like using Enum as a suffix...

2021-07-14 13:59 UTC, hhyyrylainen commented on src/general/PauseMenu.cs
> +        get
I hope this get isn't called very often...

2021-07-26 15:50 UTC, hhyyrylainen approved these changes

2021-07-26 15:56 UTC, merged