Style guide update abbreviations and ternaries
Revolutionary-Games/Thrive pull request #2464
Opened 2021-08-05 09:43 UTC by Maxonovien

**Brief Description of What This PR Does**

This PR updates the style guide in the docs to account for abbreviations and nested ternaries.

**Related Issues**

Closes #2454 , #2392 .

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

2021-08-05 09:46 UTC, Maxonovien commented
As mentioned in #2392 's comments, there is a `Sqr` abbreviation used inconsistently in `SpawnSystem.cs`. I'd vote to rule it out as an abbreviation because "Squared" is not that long. But the use is inconsistent so it would require minor rewriting anyways, I guess.

2021-08-05 10:31 UTC, hhyyrylainen requested changes
Also if you don't mind could you update the existing code to conform to the new styleguide (as you mentioned you know somep laces that don't follow the rules)?

2021-08-05 10:31 UTC, hhyyrylainen commented on doc/style_guide.md
> +  - `rect` (when related to class names and instances)
```suggestion
  - `rect` (when related to class names and variables holding instances of those classes)
```

2021-08-05 10:42 UTC, Maxonovien commented
Sure, I'll change what I spotted. If anyone has spotted further things related to abbreviations/style guide, please let me know.

2021-08-06 13:16 UTC, hhyyrylainen commented
@Maxonovien I edited the description here to fix it. You need to place the "closes" keyword before each linked issue. You can't specify a list of issues.

2021-08-12 11:03 UTC, Kasterisk commented
I think we can also add `rot` to the list for rotation to complement `pos`.  MicrobeEditor has `organelleRot` variable that pretty much uses it for example, though I believe it's the only place where the abbreviation is used.

2021-08-13 06:04 UTC, hhyyrylainen approved these changes

2021-08-13 06:05 UTC, merged

2021-08-19 12:06 UTC, hhyyrylainen commented
I just noticed that this broke save compatibility due to the renamed property. I'll make a save upgrader to remedy this situation.