2592 extinction theme
Revolutionary-Games/Thrive pull request #2594
Opened 2021-09-17 21:00 UTC by adQuid

**Brief Description of What This PR Does**

Plays extinction theme when play goes extinct. Also did some boyscouting with reused jukebox functionality.

**Related Issues**

Closes #2592 

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

2021-09-18 07:21 UTC, hhyyrylainen requested changes

2021-09-18 07:21 UTC, hhyyrylainen commented on src/microbe_stage/MicrobeStage.cs
> -
Just one tiny nitpick looks like you removed a blank line here, I think keeping the blank line here would improve readability (playing the music is not logically related to telling the HUD to show the extinction box in my mind).

2021-09-18 11:27 UTC, adQuid commented on src/microbe_stage/MicrobeStage.cs
> +            Jukebox.Instance.PlayCategory("Extinction");
```suggestion
            
            Jukebox.Instance.PlayCategory("Extinction");
```

2021-09-19 12:32 UTC, hhyyrylainen approved these changes
Code and functionality are good. I pinged you on discord about possible music license issue regarding this.

2021-09-20 21:37 UTC, merged