Major auto-evo framework updates for species splitting
Revolutionary-Games/Thrive pull request #2689
Opened 2021-10-22 15:47 UTC by hhyyrylainen

**Brief Description of What This PR Does**

Added species splitting, new species splitting when low number, and auto-evo for player
also disabled the mutated copy of player appearing each time

Has a GUI to show auto-evo (upcoming) results to the player to allow making informed decisions. May need to tweak the reproduction population bonus in the future. And also added a tutorial on the second time the player goes to the editor to highlight that they should look at it.

It seems that cloned mutated species where marked as PlayerSpecies, which might indicate that there's a serious bug in master causing species to not actually mutate or spread. Fixed in this PR.

**Related Issues**

closes #2096
closes #915

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

2021-10-30 10:56 UTC, Kasterisk requested changes

2021-10-30 11:06 UTC, hhyyrylainen commented on src/microbe_stage/editor/MicrobeEditor.tscn
> +visible = false
good catch, I tried to be careful with putting these back.

2021-10-30 11:07 UTC, hhyyrylainen commented on src/auto-evo/steps/IncreaseBiodiversity.cs
> +    ///   new offshoot species from a
added the missing few last words

2021-10-30 11:49 UTC, Kasterisk approved these changes
Maybe @adQuid can review more in-depth about the auto-evo but to me this looks good. Though I really think we need to find a better place or at least a collapse feature for the auto evo prediction panel, maybe could be put in the statistics menu once that's implemented to alleviate GUI crowding.

2021-10-30 11:51 UTC, hhyyrylainen commented
Yeah, some GUI rework would be nice. I didn't put it in the organism statistics panel as the compound balances can take up all the remaining space so I'd need to reshuffle things there and make sure scrollbars work fine in there (also the tutorial would need special logic to make sure the auto-evo results are scrolled into view automatically when the tutorial activates).

2021-10-30 11:57 UTC, Kasterisk commented
Ah I mean the general statistics menu that will be accessible through the main menu and bottom left buttons in the editor which is currently disabled. I imagine it would be quite a big feature to implement in the future.

2021-10-30 11:57 UTC, hhyyrylainen commented
At least part of the auto-evo prediction needs to be always visible when editing, otherwise the player might forget and mess over their species (though I'm about to open an issue about rebalancing the auto-evo algorithm now that the player is affected by it after this is merged).

2021-11-05 08:34 UTC, hhyyrylainen commented
I'll merge this now as no changes required reviews have come in and this is important to get in early to allow time for tweaking.

2021-11-05 09:09 UTC, merged