Optimize data points interpolation in line charts
Revolutionary-Games/Thrive pull request #2718
Opened 2021-10-31 14:13 UTC by Kasterisk

**Brief Description of What This PR Does**

Made use of Tween nodes for animating the points and got rid of the horribly optimized code in `LineChart._Process`.

**Related Issues**

Fixes #2715 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

2021-10-31 16:47 UTC, Kasterisk commented
Tested with 10 data series and each 10 data points in 3 charts. Got an increase of 700% in FPS and the UI is now very responsive whereas previously I could barely interact with it. I'd say this is a definite improvement :)

2021-11-03 18:50 UTC, hhyyrylainen requested changes
I didn't test excessively but I didn't see any performance drop anymore. Noticed just one tiny code related thing and then this is good to go.

2021-11-03 18:50 UTC, hhyyrylainen commented on src/gui_common/charts/line/LineChart.cs
> +            tween.InterpolateMethod(this, "ChangePointPos", new Vector3(i, initialPos.x, initialPos.y),
This should use `nameof(ChangePointPos)`

2021-11-04 07:10 UTC, hhyyrylainen approved these changes

2021-11-04 07:16 UTC, merged