Add support for playing a track list only once
Revolutionary-Games/Thrive pull request #2782
Opened 2021-11-19 14:18 UTC by Kasterisk

**Brief Description of What This PR Does**

Track list can now be non-repeating. Not really sure with the implementation so feel free to suggest a better approach.

**Related Issues**

Closes #2698 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

2021-11-21 09:34 UTC, hhyyrylainen requested changes

2021-11-21 09:34 UTC, hhyyrylainen commented on src/general/Jukebox.cs
> +                    track.PlayedOnce = false;
I found a bug regarding this (this reset needs to *always* happen when `category` is not null.
If you go into a new game and go extinct, the track plays fine once, but if you exit to menu and then start a new game where you go extinct again, you don't hear the extinct track again even though you should.

2021-11-21 18:38 UTC, hhyyrylainen requested changes
Still does not work:
```
Jukebox now playing from: Extinction
Jukebox: starting track: res://assets/sounds/extinct2.ogg position: 63.46594
```
Did it work for you?

2021-11-22 05:23 UTC, Kasterisk commented
Oh do you mean the track position should reset instead of continuing? From your jukebox log it seems the track is resumed at nearing the end which has quite a long silence in the audio stream but not yet ended, so that may give the impression the track never plays once it does.

2021-11-22 06:17 UTC, FuJa0815 commented
Couldn't you add a property like `NeedsToBeginFromStart`?

2021-11-22 06:35 UTC, Kasterisk commented
The actual solution would be adding a new member in MusicCategory.ReturnType enum to not continue.

2021-11-22 07:24 UTC, hhyyrylainen commented
I guess I didn't implement that? I guess there wasn't a music category before that didn't continue? Isn't the main menu category like that, or does that continue as well?

2021-11-22 07:29 UTC, Kasterisk commented
Nope, there is only one return type that is to continue. All categories currently continues including the main menu.

2021-11-22 15:40 UTC, hhyyrylainen approved these changes

2021-11-22 15:40 UTC, merged