Color picker pick rewrite
Revolutionary-Games/Thrive pull request #3055
Opened 2022-01-28 11:27 UTC by 84634E1A607A

**Brief Description of What This PR Does**
Rewrote color picker's pick button function. Temp fix for Godot issue https://github.com/godotengine/godot/issues/57343

**Related Issues**
Fixes #2803

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2022-02-09 19:40 UTC, hhyyrylainen requested changes
I experienced the same kind of major lag as @RacerBG when I increased the window size a lot. I think the read from the rendered image starts taking up too long and causes a long queue of input events to process. To solve this, I think we should just sample the colour under the mouse in _Process every 100-200 milliseconds so that we aren't reading so much data from the GPU and converting that over to data readable from C#.

2022-02-09 19:40 UTC, hhyyrylainen commented on src/gui_common/TweakedColourPicker.cs
> +        baseControl.RemoveChild(pickerButton);
Is it possible to overwrite the default connection (so unconnect first) and then just link us to the default button? That would mean we mess with Godot's internals less here.

2022-02-10 14:53 UTC, hhyyrylainen commented on src/gui_common/TweakedColourPicker.cs
> +        baseControl.RemoveChild(pickerButton);
I guess we don't know the connected object and method name so we can't actually call `Disconnect` here.

2022-02-12 12:31 UTC, hhyyrylainen commented on src/gui_common/TweakedColourPicker.cs
```suggestion
    private bool presetsVisible = true;
    private PickerMode mode;

    private bool pickingColor;
    private Color colorBeforePicking;
    private float pickerTimeElapsed;

```

2022-02-12 12:32 UTC, hhyyrylainen commented on src/gui_common/TweakedColourPicker.cs
> +        if (pickerTimeElapsed < 0.2)
```suggestion
        if (pickerTimeElapsed < 0.2f)
```

2022-02-12 13:03 UTC, hhyyrylainen approved these changes
Seems to perform pretty well even at 4K now, which should be good enough.

2022-02-12 13:06 UTC, Kasterisk approved these changes

2022-02-12 13:21 UTC, RacerBG reviewed
The lag is gone. Now it is around 1 FPS compared 50-70 FPS reduction in my first test.

But I noticed another problem: Now when I stop the cursor movement, while I'm still in color picker mode, the "cross" (the horizontal and vertical lines) continue to loop over the colors. Also while moving the cursor, the cross lags behind it even though the game is not lagging.

2022-02-12 13:24 UTC, hhyyrylainen commented
> But I noticed another problem: Now when I stop the cursor movement, while I'm still in color picker mode, the "cross" (the horizontal and vertical lines) continue to loop over the colors. Also while moving the cursor, the cross lags behind it even though the game is not lagging.

Isn't that just how it works anyway? If you hover over the colour picker itself it ends up updating itself and then reading the updated value causing weirdness.
The mouse lag is an unfortunate side effect of only updating 4 times per second. I suppose we could read the screen texture a few times a second and read from that whenever we want (which should also fix the lag), but that would be harder to implement and I don't think we need to spend the time to code that.

2022-02-12 13:28 UTC, hhyyrylainen commented
I'll merge this because this makes the situation much better (and I think fixes a crash). The colours going crazy is a problem with Godot's builtin colour picker as well. If someone really wants the last part of my previous comment can be done by a separate PR.

2022-02-12 13:28 UTC, merged

2022-02-12 13:28 UTC, RacerBG commented
> > But I noticed another problem: Now when I stop the cursor movement, while I'm still in color picker mode, the "cross" (the horizontal and vertical lines) continue to loop over the colors. Also while moving the cursor, the cross lags behind it even though the game is not lagging.
> 
> Isn't that just how it works anyway? If you hover over the colour picker itself it ends up updating itself and then reading the updated value causing weirdness. The mouse lag is an unfortunate side effect of only updating 4 times per second. I suppose we could read the screen texture a few times a second and read from that whenever we want (which should also fix the lag), but that would be harder to implement and I don't think we need to spend the time to code that.

I don't know if we are talking about the same thing. I did this:

1. Switched in to color picker mode.
2. Moved the cursor over the colors window or square in a fast manner.
3. Stopped the movement while still the cursor was in the boundaries of the colors window.
4. The cross started to loop over the current cursor x, y position and the last cursor x, y position endlessly.

2022-02-12 13:31 UTC, hhyyrylainen commented
That "oscillation" is probably caused by the colour being updated only like 5 times per second so with the fast movement it sees the previous colour, changes to that, and then the new colour ends up being sampled as the previous data was still in use, or something. The move to storing the window render buffer and updating the picked colour from it immediately should fix that, but as I said, I don't think this is a big enough problem to warrant a lot of effort to fix. The oscillation stops if you move the cursor over another element than the colour picker, right?

2022-02-12 13:33 UTC, RacerBG commented
> That "oscillation" is probably caused by the colour being updated only like 5 times per second so with the fast movement it sees the previous colour, changes to that, and then the new colour ends up being sampled as the previous data was still in use, or something. The move to storing the window render buffer and updating the picked colour from it immediately should fix that, but as I said, I don't think this is a big enough problem to warrant a lot of effort to fix. The oscillation stops if you move the cursor over another element than the colour picker, right?

Right. And the same behaviour doesn't happen when I try to select a color from the cell surroundings for example.