Fixed changing organelle rotation in place
Revolutionary-Games/Thrive pull request #3065
Opened 2022-02-01 07:12 UTC by Kasterisk

**Brief Description of What This PR Does**

Added rotation equals check in MoveOrganelle's anti-exploit position equals check so that rotating an organelle in place actually rotates the organelle into that particular angle when you finishes the action.

Steps to reproduce the original issue
- Place pilus
- Start organelle move action
- Rotate it in place in a different angle
- Place it
- It reverts back to the previous angle

**Related Issues**

Fixes #2993 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2022-02-03 07:53 UTC, hhyyrylainen requested changes
This allows a free move exploit.

If I move an organelle to the exact same position and rotation, then it doesn't take MP and the next move takes -5MP like usually, however if I rotate the organelle and place it at the current location, this makes the next move free 0MP, even though it should cost MP.

2022-02-13 10:58 UTC, Kasterisk commented
I don't know this seems like an underlying flaw with the free move logic itself. So as far as I understand it, a move action is free if it satisfies these three conditions: an organelle is moved within current session, added within current session or rotated in place (as per the docs). Looks like the former and latter is inherently exploitable, while I've fixed the first one being exploitable in #2400, this bugfix-fix seems to unmask the problem with the last.

2022-02-13 11:02 UTC, hhyyrylainen commented
The logic should be that placing the organelle at the exact place it is at, should be free (and basically cancel the move action). And any other move (the first time when done in an editor session for an organelle) should cost MP. Perhaps rotating in-place should also cost MP? This PR probably needs reworking once https://github.com/Revolutionary-Games/Thrive/pull/2445 is done.

2022-02-13 11:08 UTC, Kasterisk commented
> Perhaps rotating in-place should also cost MP?

No problem for me.

> This PR probably needs reworking once https://github.com/Revolutionary-Games/Thrive/pull/2445 is done.

Well in that case, shouldn't it be better to fix the issue this PR is trying to solve in that PR (or the free move issue in general)? This can be closed instead.

2022-02-13 11:10 UTC, hhyyrylainen commented
Probably yeah, if you are up for looking at this again afterwards.
Btw it looks like currently the new PR will ignore in-place rotation when determining costs: https://github.com/Revolutionary-Games/Thrive/pull/2445/files#diff-b68cb07ad85aa6847e8f3075164777676512f49a460148d05e08701f87f9af4dR27

2022-02-13 11:18 UTC, Kasterisk commented
Yet another thing to consider in the code @FuJa0815. I'll close this in the meantime.

2022-02-13 11:19 UTC, closed without merging