Made environment and compounds panel collapsed state be saved
Revolutionary-Games/Thrive pull request #3327
Opened 2022-05-07 16:13 UTC by Kasterisk

**Brief Description of What This PR Does**

Made their collapsed states savable, refactored the expand/collapsed logic a bit while working. Also shouldn't their collapsed state have already been kept after returning from the editor since past versions?

**Related Issues**

Fixes #3320.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2022-05-08 16:23 UTC, RacerBG approved these changes
I had never thought about this, it's nice to have this QoL fix.

2022-05-08 18:13 UTC, hhyyrylainen requested changes
I guess it's fine if it is saved in the save files, though I'm not sure if that was what was the intention with the original issue?
Anyway I can accept the saving. I spotted one potentially incorrect visibility change, so that should be confirmed it is intended before merging.

2022-05-08 18:13 UTC, hhyyrylainen commented on src/microbe_stage/MicrobeStage.tscn
> +visible = true
Unintended change?

2022-05-09 08:47 UTC, Kasterisk commented on src/microbe_stage/MicrobeStage.tscn
> +visible = true
Probably. Now fixed.

2022-05-09 09:17 UTC, hhyyrylainen approved these changes

2022-05-09 10:00 UTC, merged