Made toxins fire relative to cell's actual orientation
Revolutionary-Games/Thrive pull request #3374
Opened 2022-05-28 15:51 UTC by Oliveriver

**Brief Description of What This PR Does**

Cells now fire toxins relative to their rotation, not their intended rotation (LookAtPoint). Needed now that variable rotation speeds are in the game.

**Related Issues**

Fixes #3372 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2022-05-28 17:17 UTC, hhyyrylainen requested changes

2022-05-28 17:17 UTC, hhyyrylainen commented on src/microbe_stage/Microbe.Interior.cs
> +        var direction = new Vector3((float)-Math.Sin(Rotation.y), 0, (float)-Math.Cos(Rotation.y)).Normalized();
Don't use angles unless absolutely required, use quaternions instead. Also this doesn't get the global rotation, so this'll be incorrect in microbe colonies.

I suggest using something like `GlobalTransform.basis.Quat()` and working from there.

2022-05-31 03:15 UTC, buckly90 commented
Couldn't find anything gone wrong in this PR, everything behaved well.

Great job!

2022-05-31 13:54 UTC, hhyyrylainen approved these changes
Code looks good.

2022-05-31 13:54 UTC, merged