Validate cell type name in multicellular editor
Revolutionary-Games/Thrive pull request #3387
Opened 2022-06-07 09:49 UTC by jacobperron

**Brief Description of What This PR Does**

* Factor out logic for name validation from CellBodyPlanEditorComponent into EarlyMulticellularEditor
* Pass validation function to CellEditorComponent to use when name changes

**Related Issues**

Closes #3168 
**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2022-06-07 09:51 UTC, jacobperron commented
Opening as draft, since it still needs some changes to actually make sure that name-only changes to the cell type are applied when leaving the cell editor tab. I'm looking for feedback on a good way to handle this (and also the current approach to cell type name validation).

2022-06-09 09:21 UTC, hhyyrylainen commented
This is where the name is applied: https://github.com/Revolutionary-Games/Thrive/blob/02730b77400fb535d146945aa66efd944e674c6a/src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs#L496

As for your changes, I think they are on the right track. The only slight problem I see is  that if a name is unchanged then it will be detected as a duplicate of itself, at least I think purely by looking at the code that that might happen.

2022-06-11 21:19 UTC, jacobperron commented
Thanks @hhyyrylainen, I think I've resolved the issue of detecting the current name as a duplicate. Ready for a more thorough review!

2022-06-12 13:25 UTC, hhyyrylainen requested changes
I noticed at least one problem:
- Duplicate the stem type and call it "Stem2"
- Edit the stem type
- Edit the name to be "Stem", see it get red
- Now backspace that edit away, for some reason the name is still red

Seems at least that the thing being the same name as before is not a problem as I feared earlier.

Probably caused by the fact that if the name is the same it doesn't run the validation.

2022-09-19 12:53 UTC, hhyyrylainen commented
I'll remove this from the next release milestone as this doesn't seem to be actively worked on. Let me know when this is picked up again and I'll adjust milestones again.

2022-10-25 08:52 UTC, jacobperron commented
Sorry, I won't have the time to continue working on this any time soon. Feel free to close or take over the PR.

2023-06-05 11:47 UTC, hhyyrylainen commented
I'll close this PR as a pretty old one that is quite unlikely to resume work anytime soon so the upcoming history rewrite will cause this PR to basically conflict with everything and need manual fixing.

2023-06-05 11:47 UTC, closed without merging