Make player able to move to any inhabitants or their adjacent
Revolutionary-Games/Thrive pull request #3587
Opened 2022-07-23 01:26 UTC by 84634E1A607A

**Related Issues**
Maybe there isn't one?

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2022-07-23 01:32 UTC, 84634E1A607A commented
I found myself that if I went extinct from two patches in a row, after entering the editor the second extinction disappeared (I still have population in that patch). Is it because #3460 ?

2022-07-23 08:06 UTC, hhyyrylainen commented
> I found myself that if I went extinct from two patches in a row, after entering the editor the second extinction disappeared (I still have population in that patch). Is it because 

It shouldn't be related. More likely the external effects was not enough to overwhelm the population auto-evo calculated for you in that one patch you actually survived. This would be a pretty hard auto-evo interaction with gameplay design problem to solve.

2022-07-26 10:48 UTC, hhyyrylainen requested changes
I didn't notice any issues in playtesting, I have one suggestion as to make one comment clearer.

2022-07-26 10:48 UTC, hhyyrylainen commented on src/microbe_stage/editor/PatchMapEditorComponent.cs
> +        // Can move to any patch that player species inhabits or their adjacent
```suggestion
        // Can move to any patch that player species inhabits or is adjacent to such a patch
```

2022-07-26 10:48 UTC, hhyyrylainen approved these changes
This is a small change and it's been open for a while, so I'll go ahead and commit my own suggestion and merge this.

2022-07-26 10:59 UTC, merged