Split timeline and tree so that timeline is always shown
Revolutionary-Games/Thrive pull request #3669
Opened 2022-08-07 03:10 UTC by 84634E1A607A

**Related Issues**
Fixes #3632

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2022-08-09 08:37 UTC, hhyyrylainen commented
What's the approach used here? To me it seems like maybe this now re-renders each frame the mouse drags around or what? Based on a quick look of the drag container being removed. I think maybe instead what this should do is use a scroll container that has the timeline at the top and then the bottom view would use the drag container. Then this is just a case of needing a bit of code to sync the horizontal values of the timeline and the draggable tree view.

2022-08-09 08:42 UTC, 84634E1A607A commented
I'm not quite sure. The current DraggableScrollContainer seems buggy. ScrollContainer is buggy as well. The key concept here is to keep scale property unchanged but calculate position & size & etc codewide. This allows for full control to the Tree content instead of coming up with hacky workarounds for all those Godot limitations & bugs.

2022-08-09 08:58 UTC, 84634E1A607A commented
Plus this seems to improve performance.

2022-08-09 09:05 UTC, hhyyrylainen commented
> Plus this seems to improve performance.

Okay, I guess I need to actually read the code to figure out how this works... some extra comments explaining how the overall approach works would be highly appreciated by me (and on the offchance that someone else also looks at this, they would benefit as well).

2022-08-09 11:39 UTC, 84634E1A607A commented
> I need to actually read the code to figure out how this works...

As for why this improves performance... I don't know either.

2022-08-10 02:23 UTC, 84634E1A607A commented
I am now confident that EvolutionaryTree will run 60 fps no matter how bit the tree is.

2022-08-12 20:33 UTC, Nunez2196 approved these changes

2022-08-12 20:55 UTC, Nunez2196 commented
I tested this a bit while reviewing. Worked pretty good, even on my laptop.

2022-08-13 02:05 UTC, 84634E1A607A commented
Line corners are now smooth.

2022-08-14 05:52 UTC, Kasterisk requested changes
A couple of observations:
- I think the timeline shouldn't be affected by zooming, the numbers shouldn't shrink or grow, instead the "length" is what changes. I can't think of more good example of how this works but MS Word's ruler bar might be a good reference?
- The cursor immediately changes to the default icon everytime I mouse over the tree area.

2022-08-14 06:05 UTC, 84634E1A607A commented
The cursor mode is "Drag" but somehow it isn't a hand.

2022-08-14 06:18 UTC, 84634E1A607A commented
> I think the timeline shouldn't be affected by zooming

Why? Then its font size is not changed accordingly, and it may seem strange when scrolled small.

2022-08-14 06:48 UTC, Kasterisk commented
To rephrase that, I mean the visual _size_ of the timeline bar shouldn't be affected as I mentioned with the time ticks (also the line itself shrinks when you zoom out). If it were to be like this, surely nothing on the timeline is readable once you zoom out far enough right?

What I suggest is something like this:
![timeline](https://user-images.githubusercontent.com/54026083/184525797-d4d1133e-b160-4d12-934a-8df4b81b0620.gif)

2022-08-14 07:26 UTC, 84634E1A607A commented
I understand, but I still think that it will be a little strange.

2022-08-14 08:49 UTC, Kasterisk requested changes
Timeline starting to look very good now. However, the cursor for the tree area is now apparently on reverse. When hovering any of the circles, the normal icon is shown, but outside of it, the blue variant of the cursor is shown which is usually used for interactable elements (patches on patch map). Obviously this is the wrong way around.

2022-08-14 08:56 UTC, 84634E1A607A commented
Seems like other buttons are using the def Arrow cursor, so I'll just set tree cursor to default.

2022-08-14 09:02 UTC, Kasterisk approved these changes
I'm satisfied with the results.

2022-08-14 12:25 UTC, hhyyrylainen requested changes
I have a few code related comments. I couldn't really spend the time to try to fully understand the changes but they looked overall fine. Especially moving more stuff into the evolutionary tree scene is good.
I noticed one slightly not intuitive part in playtesting: when I scroll with the mouse the scroll is not centered around the mouse. So for example if I zoom out all the way and then place my mouse in the upper right corner and zoom in, the evolutionary tree ends up being zoomed to the top left corner. That's now how UI zooming should work. So the zooming should be fixed to be centered around the current cursor position.
Also there's now a slight graphical problem when zooming out, the circles have the bottom few pixels cutoff so the botton sides of the cirles don't look like circles anymore. This isn't super critical but if there's an easy fix I'd like this to be fixed.

2022-08-14 12:25 UTC, hhyyrylainen commented on src/auto-evo/EvolutionaryTree.cs
> +    // ReSharper disable 4 times RedundantNameQualifier
I think it's better to use the disable and then enable comment rather than this "4 times" thing.

2022-08-14 12:25 UTC, hhyyrylainen commented on src/auto-evo/EvolutionaryTree.cs
> +    private const float SMALL_FONT_SIZE = 14.0f;
Would it be possible to actually get the font size from the actually used font?

2022-08-14 12:25 UTC, hhyyrylainen commented on src/auto-evo/EvolutionaryTree.cs
> +    ///   All EvolutionaryTreeNodes are in this group so that they works radio.
```suggestion
    ///   All EvolutionaryTreeNodes are in this group so that they work as radio buttons.
```

2022-08-14 12:25 UTC, hhyyrylainen commented on src/auto-evo/EvolutionaryTree.cs
> +        tree.Connect("mouse_exited", this, nameof(MouseExit));
Why are these signals not setup in Godot editor?

2022-08-14 12:25 UTC, hhyyrylainen commented on src/auto-evo/EvolutionaryTree.cs
> +            // timeline.RectMinSize = new Vector2(0, sizeFactor * TIMELINE_HEIGHT);
What's this commented out line of code for?

2022-08-14 12:25 UTC, hhyyrylainen commented on src/auto-evo/EvolutionaryTree.cs
> +        latoSmallItalic.Set("size", sizeFactor * SMALL_FONT_SIZE);
Here's the font size, so I assume with a similar call in _Ready this could get the default font size automatically and not have to assume it is 14.

2022-08-14 12:25 UTC, hhyyrylainen commented on src/auto-evo/EvolutionaryTree.cs
> +            // We draw vertical line a little longer so the turning point is good.
```suggestion
            // We draw vertical line a little longer so the turning point looks better.
```

2022-08-15 14:01 UTC, hhyyrylainen requested changes
Everything else except the zooming seems good now.

Here's how you can see how the zooming is still not the best. Zoom out all the way, place the cursor on one of the species nodes on the right side and start scrolling in. You'll end up zoomed in at the center of the graph instead of at the right side.

2022-08-15 15:09 UTC, 84634E1A607A commented
That's because the tree size is smaller than the container horizontally. When you zoom in the tree is once again aligned to the lefttop corner. I don't think this can be fixed.

2022-08-15 15:25 UTC, hhyyrylainen commented
I kind of suspected as much, but I think GUI libraries solve this by having "virtual" size for their items that is larger than the size they take up, that way they can implement mouse zoom properly. There's anyway the issue with the non-round circle bottoms so I could open also an issue about this, if you don't think you can solve this now.

2022-08-16 07:46 UTC, hhyyrylainen approved these changes
I'll open issues for my remaining playtesting things I found wrong with this.

2022-08-16 07:47 UTC, merged

2022-08-16 07:53 UTC, hhyyrylainen commented
Opened follow up issues:
- https://github.com/Revolutionary-Games/Thrive/issues/3715
- https://github.com/Revolutionary-Games/Thrive/issues/3716