AI will now usually choose not to eat what it can't digest
Revolutionary-Games/Thrive pull request #4443
Opened 2023-08-20 22:48 UTC by adQuid

**Brief Description of What This PR Does**

Adds a rolled chance on target acquisition to probably not engulf things it can't digest.

**Related Issues**

fixes #4440 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2023-08-21 05:58 UTC, hhyyrylainen commented on simulation_parameters/Constants.cs
> +    public const float AI_BAD_ENGULF_CHANCE = 0.25f;
Even though other people have commented incorrectly the AI constants, could you make this into a proper XML comment?

2023-08-21 20:06 UTC, buckly90 approved these changes
This works just as well as I hoped, great stuff!

I would say that the value for AI_BAD_ENGULF_CHANCE feels a bit too big. Somewhere around 10-15% might be better.

I noticed that cells that chose to attempt engulfing something they couldn't digest would begin to use toxins as well. I assume this behavior normally wouldn't be an issue, but with digestability now part of the equation, hunting with toxins versus engulfing might need to be seperated...
While you are free to try fixing that in this PR, I'll otherwise go ahead and open an issue about this once this PR is merged.

2023-08-22 12:01 UTC, hhyyrylainen commented
I think we ought to leave out the more complex change for later, and open an issue about it to not forget about it.

@adQuid is there a reason why you haven't checked the PR workflow first item (`PR author has checked that this PR works as intended and doesn't--`)?

2023-08-22 12:05 UTC, hhyyrylainen requested changes
The eating decision logic is pretty complex but as far as I can parse it in my head it is correct. I noticed one code comment typo, well at least I think it is one, that didn't get fixed. If that's fixed then with buckly's testing I think this is fine to merge.

2023-08-22 12:05 UTC, hhyyrylainen commented on simulation_parameters/Constants.cs
> +    ///   Probability, rolled at each AI step (which very often), that the AI will try to engulf something it can't eat
I'm still seeing the "(which very often)" part which doesn't sound grammatically correct to me here.

2023-08-23 14:18 UTC, hhyyrylainen commented on simulation_parameters/Constants.cs
> +    ///   Probability, rolled at each AI step (which very often), that the AI will try to engulf something it can't eat
And now the line is too long :laughing:

2023-08-23 15:47 UTC, hhyyrylainen approved these changes

2023-08-23 15:47 UTC, merged

2023-08-23 15:47 UTC, hhyyrylainen commented
@buckly90 do you want to open that follow up issue or should I?

2023-08-24 07:04 UTC, hhyyrylainen commented
I opened the follow up issue so that I can move on: https://github.com/Revolutionary-Games/Thrive/issues/4445 let me know if I understood incorrectly what it should have.