Log becoming multicellular in the timeline
Revolutionary-Games/Thrive pull request #4527
Opened 2023-10-16 18:38 UTC by ender-titan1

**Brief Description of What This PR Does**

This PR logs becoming multicellular in the timeline

**Related Issues**

Closes #3154

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [X] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2023-10-16 19:03 UTC, hhyyrylainen commented on assets/models/easter_eggs/GooglyEyeCellFlee.anim
Looks like you allowed Godot to do these changes I've always kept reverting... Does this model and the two animations still work?

2023-10-16 19:04 UTC, hhyyrylainen requested changes

2023-10-16 19:04 UTC, hhyyrylainen commented on src/microbe_stage/MicrobeStage.cs
> +            new LocalizedString("TIMELINE_PLAYER_BECAME_MULTICELLULAR", Player.Species.FormattedName),
In the future becoming multicellular is not exclusive to the player, so I think the translation key should be "TIMELINE_SPECIES_BECAME_MULTICELLULAR" (and the text needs to be adjusted as well if it makes explicit reference to the player).

2023-10-16 19:52 UTC, ender-titan1 commented on assets/models/easter_eggs/GooglyEyeCellFlee.anim
The slime jet animation appears to work for sure, as for the other ones, I don't really know how to check.

2023-10-17 07:57 UTC, hhyyrylainen approved these changes
This seems fine, though right now the species becoming multicellular is logged as 100 Myr earlier in the global timeline as the local one. Someone might notice this at some point and report it as a bug...

2023-10-17 08:20 UTC, merged