Add middle mouse button panning for strategy camera
Revolutionary-Games/Thrive pull request #4747
Opened 2023-12-25 18:04 UTC by CI09

**Brief Description of What This PR Does**

This PR adds middle mouse button panning for strategy camera and input for gameplay middle mouse button panning in input  map.

**Related Issues**

Closes #4271 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2024-01-02 07:22 UTC, hhyyrylainen requested changes
This looks just about how I'd do the core implementation. Besides the code comments I have two thoughts:
- How does the microbe editor do this? Wouldn't it be nice to have the same mouse input trigger both actions?
- The new input should be added to the input options JSON so that it can be rebound to a different key if someone wishes to do so.

2024-01-02 07:22 UTC, hhyyrylainen commented on src/society_stage/StrategicCamera.cs
> +        if (!Visible)
Shouldn't the mouse pan still be reset even if this is not visible?
Also eating the mouse up event is rarely a good idea.

2024-01-02 07:22 UTC, hhyyrylainen commented on src/society_stage/StrategicCamera.cs
> +    public bool PanCameraWithMouse(float delta)
```suggestion
    public bool PanCameraWithMouse(float dummy)
```

I'd name the parameter like that to ensure no one later accidentally tries to use it and gets surprised when the variable doesn't actually contain the delta.

2024-01-02 13:27 UTC, CI09 commented
> * How does the microbe editor do this? Wouldn't it be nice to have the same mouse input trigger both actions?
I think microbe editor utilizes e_pan_mouse. I am pretty sure they work the same way, but some inputs had their e_ and g_ counterparts, so I tried to make it consistent. It can be removed if unnecessary.

2024-01-03 14:59 UTC, hhyyrylainen approved these changes
This change looks fine. I'll separately add the missing entry in the input options for `e_pan_mouse`.

2024-01-03 15:02 UTC, merged

2024-01-03 15:03 UTC, hhyyrylainen commented
Actually I'll need to do some other tweaks as I noticed that the mouse up handling is inconsistent *and* multiple of the mouse pan callbacks actually use the delta value *after* specifying they don't want to use it.

2024-01-03 16:47 UTC, hhyyrylainen commented
And I found a bunch of bugs that had snuck in at some point (I don't suspect this PR was the cause) about the mouse panning. I fixed all of that and made the strategy mode mouse pan snappy to exactly mirror mouse movements: https://github.com/Revolutionary-Games/Thrive/pull/4759