Hardcore mode
Revolutionary-Games/Thrive pull request #5160
Opened 2024-05-27 14:51 UTC by CI09

**Brief Description of What This PR Does**

This PR adds hardcore mode - removes standard saving from game together with quicksaves and in place of auto-saves a save is performed that writes **into one save name selected upon save creation**.

**Related Issues**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2024-05-27 21:02 UTC, HexapodPhilosopher reviewed
No bugs found. It is lacking a save on returning to the main menu, though. I was able to revert a bit by using that.

2024-05-28 05:27 UTC, hhyyrylainen commented
I didn't check but this mode should also suppress the warning for exiting without saving as this should force the save when exiting so that warning is not incorrectly shown.

2024-05-31 07:32 UTC, hhyyrylainen requested changes
This needs more bulletproofing against players exploiting the fact that the game doesn't save when exiting in this mode before I think this is a polished enough feature to include in the game.

2024-05-31 08:09 UTC, HexapodPhilosopher commented
Also, wouldn't it make sense to include the checkbox for this in the Difficulty settings, rather than Misc? It's where most people would look for it.

2024-07-22 07:58 UTC, hhyyrylainen commented
What's the current progress on this? Last I checked this was very brittle in terms of how well it saves and keeps the player from very easily cheating in the difficulty mode.

2024-07-22 12:49 UTC, CI09 commented
I got stuck at saving upon leaving so help would be useful. It's not mandatory feature though so you know...

2024-07-22 12:57 UTC, hhyyrylainen commented
That's fine, I'll just take this off the list of PRs I need to review.

2025-02-20 02:18 UTC, closed without merging