Convert turn algorithm to not be so dependent on cursor position
Revolutionary-Games/Thrive pull request #5242
Opened 2024-06-20 01:05 UTC by adQuid

**Brief Description of What This PR Does**

Changes calculations to pretend the cursor is 90 degrees to the left or right as appropriate, unless the cursor is facing very close to the front. Some turning constants were changed as well to adjust for this.

**Related Issues**

fixes #4764 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2024-06-20 06:36 UTC, hhyyrylainen commented on src/microbe_stage/systems/MicrobeMovementSystem.cs
> +            lookVector = lookVector.Normalized();
Why is the length now calculated twice? (Normalization of a vector must calculate the length).

2024-06-20 06:36 UTC, hhyyrylainen commented on src/microbe_stage/systems/MicrobeMovementSystem.cs
> +        // Simplify turns to 90 degrees to keep consistant turning speed
```suggestion
        // Simplify turns to 90 degrees to keep consistent turning speed
```
typo

2024-06-20 06:39 UTC, hhyyrylainen commented on src/microbe_stage/systems/MicrobeMovementSystem.cs
> +        if ((position.Rotation * Vector3.Forward).SignedAngleTo(lookVector, Vector3.Up)
`(position.Rotation * Vector3.Forward).SignedAngleTo(lookVector, Vector3.Up)`

could be extracted as a variable to not have to calculate that number twice (I'm pointing this out as the movement system runs for each microbe on each game simulation update).

2024-06-20 07:39 UTC, hhyyrylainen requested changes
I tried playtesting this a bit and in my experience small mouse movements are still fine but larger ones now cause a very noticeable "snap" once the target vector is far away enough. I feel like that snap doesn't feel good. I think instead this algorithm should just exaggerate the look vector with a (linear) scaling based on how far away the mouse is. That would still speed up the rotation without having to put the mouse really far away past the target rotation you want and without having a very noticeable snapping point in the rotation.

2024-07-23 08:00 UTC, hhyyrylainen requested changes
I'm still getting pretty weird rotation results:

[2024-07-23 10-56-50.webm](https://github.com/user-attachments/assets/f1c4af4b-1323-44fe-bf64-c5efdb8c15e6)


That should be with the latest commit on this branch `5fb9a41fa31ab9d48a55e10c720c40443b40fe37`.

2024-07-24 02:02 UTC, adQuid commented
> I'm still getting pretty weird rotation results:
> 
>  2024-07-23.10-56-50.webm 
> That should be with the latest commit on this branch `5fb9a41fa31ab9d48a55e10c720c40443b40fe37`.

you were very correct; I had some issues with my trigonometry and covered it up with my smoothing threshold. I've now reworked it.

2024-07-24 11:49 UTC, hhyyrylainen commented on src/microbe_stage/systems/MicrobeMovementSystem.cs
> +        // linear function reaching 1 at CELL_TURN_INFLECTION_RADIANS
```suggestion
        // Linear function reaching 1 at CELL_TURN_INFLECTION_RADIANS
```

2024-07-24 11:50 UTC, hhyyrylainen approved these changes
I can't say I pretend to understand the math, but in game testing results no longer show any weirdness and it feel good (I'm sure after getting used to this for a bit I'll wonder why rotation was ever slower).

2024-07-25 06:41 UTC, merged