Remove Old Mutation Code
Revolutionary-Games/Thrive pull request #5410
Opened 2024-08-26 13:36 UTC by GameDungeon

**Brief Description of What This PR Does**

This removes the old mutation code. I believe that this breaks save compat.

**Related Issues**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2024-08-26 13:49 UTC, hhyyrylainen commented on simulation_parameters/SimulationParameters.cs
Shouldn't the random chance lists be also removed as if I remember right these were the only uses for those?

2024-08-26 13:51 UTC, hhyyrylainen commented on src/auto-evo/mutations/CommonMutationFunctions.cs
> +            var mutationList = mutationStrategy.MutationsOf(mutated, mp, true)?.OrderBy(_ => random.Next()).ToList();
Wouldn't FirstOrDefault be better here? That avoids potentially building a list of 100 items but then discarding all but the first one.

2024-08-26 13:52 UTC, hhyyrylainen commented
This is a good change to do to remove outdated code.

I don't see why this would break save compatibility as this just removes a property which when loaded from a save will be ignored in the future. Or does the removal of a class the JSON loader would want to instantiate cause issues?

2024-08-26 13:58 UTC, GameDungeon commented
I didn't know how that was handled so I just put a warning to make sure. I guess I should probably just test it.

2024-08-26 14:10 UTC, GameDungeon commented
Ok, I was wrong, everything loads fine

2024-08-26 14:12 UTC, GameDungeon commented on simulation_parameters/SimulationParameters.cs
I tried removing those and everything breaks, so I decided to ignore those for now.

2024-08-26 14:14 UTC, hhyyrylainen commented on simulation_parameters/SimulationParameters.cs
??? how does that happen? Wouldn't it be better to figure out why and remove all the outdated code that is no longer needed at once?

2024-08-26 14:17 UTC, GameDungeon commented on simulation_parameters/SimulationParameters.cs
When I get home later I can explore it more, but I think the entire organelles simulation instance was null or something like that.

2024-08-26 22:19 UTC, GameDungeon commented on simulation_parameters/SimulationParameters.cs
I can no longer reproduce the issues A had before, so I must have changed something else by mistake.

2024-08-27 07:42 UTC, hhyyrylainen requested changes
There's a pretty major issue now: the species generated are random now instead of always the same (as I think was the case previously in the benchmark). This will make benchmark results less consistent than before (not that they were super consistent before).

2024-08-27 07:43 UTC, hhyyrylainen commented
For the record I checked that the `random` state is the same before the `GenerateRandomSpecies` method is called. So there has to be something in there that doesn't consistently use random state.

2024-08-27 10:37 UTC, GameDungeon commented
AddOrganelleAnywhere's random is not passed in, which is the issued.

2024-08-27 10:40 UTC, hhyyrylainen commented
That sounds very plausible. Would you be able to make that change? That would be great for this to then be merged as keeping the benchmark at least a bit more consistent would be excellent.

2024-08-27 11:22 UTC, GameDungeon commented
I can in a couple hours from now.

2024-08-28 08:24 UTC, hhyyrylainen commented
I'll try to find a good new seed for the benchmark as it now causes many big cells that start dying and playing the damage sound really loudly.

2024-08-28 11:17 UTC, hhyyrylainen approved these changes
I couldn't find an absolutely perfect seed so I've opened up a follow up issue but I'll merge this now as it is much better to have a consistent benchmark species than not have that: https://github.com/Revolutionary-Games/Thrive/issues/5424

2024-08-28 11:20 UTC, merged