Improve membrane visuals
Revolutionary-Games/Thrive pull request #5599
Opened 2024-10-16 14:12 UTC by dligr

**Brief Description of What This PR Does**

- Decreases transparency (especially visible on lighter patches and for bigger microbes)
- Improves UV mapping for bump maps. Specifically, this removes bump map stretching and 
instead makes

Before/after:
![image](https://github.com/user-attachments/assets/3d40bf66-b256-4f5a-b725-9b6c13dff9f8)

**Related Issues**

--

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

2024-10-16 19:26 UTC, hhyyrylainen commented on src/microbe_stage/MembraneShapeGenerator.cs
This doubles the size of the UV data for all membranes (which there can be hundreds). Would it be possible to calculate the UV2 value in the vertex shader as it looks like it is just the vertex coordinates multiplied by a constant? I think it is possible to access the vertex position in the vertex shader in godot and write it to the UV2 variable so that it is then available in the fragment shader. This way the GPU can just calculate it (which is probably even faster due to data locality) just before running the pixel shaders.

2024-10-16 20:01 UTC, dligr commented on src/microbe_stage/MembraneShapeGenerator.cs
Since mesh's vertices are moved real-time, this approach causes normals to 'drift' along the membrane surface.

I think that once new membrane textures are made, we would be able to use the same UVs for both texture and normals, so we wouldn't need two arrays.

2024-10-16 20:13 UTC, hhyyrylainen commented on src/microbe_stage/MembraneShapeGenerator.cs
But hang on couldn't the animation which is calculated in the shader first copy the original data to the UV2 channel and *then* apply the animation?

2024-10-18 07:16 UTC, hhyyrylainen requested changes
Is the visuals still much more opaque in the center of cells? Also one tiny syntax style thing I noticed.

2024-10-18 07:16 UTC, hhyyrylainen commented on shaders/Membrane.gdshader
> +	UV2 = VERTEX.xz * 0.05f;
There's a tab here

2024-10-18 08:04 UTC, hhyyrylainen commented
I assume it is fine if I make a separate simple commit from fixing the UVs for the bump map and merge that in and leave the opaqueness change for later?

2024-10-23 11:45 UTC, hhyyrylainen commented
So this is now just a PR increasing the opacity of the membranes. In order for this to be merged, next this needs positive feedback about the graphics change (so far there's been some disagreement that this is a good change).

2024-10-24 18:08 UTC, Nein99 commented
I definitely support this change, as I've been playing with it a bit and it not only increases visibility of small cells on light backgrounds, but in my opinion it significantly improves the "under a microscope" look that I presume we want for the microbe stage.

Here's a screenshot I took of gameplay without this change. Bacteria are almost invisible in screenshots on light backgrounds, and are mainly only visible in game because they're moving around.
![image](https://github.com/user-attachments/assets/06834f8d-7a3a-4ac6-8260-e41e41f09260)

Here's some screenshots I took of bacteria while playing with this change (merged into my fork, so ignore the bioluminescence):
![image](https://github.com/user-attachments/assets/ae934b9f-5015-4fa2-9ebe-fe1c51357d62)
![image](https://github.com/user-attachments/assets/37bf27ca-6abe-40fe-ba3e-32da159a9999)
![image](https://github.com/user-attachments/assets/34321546-6994-4297-88ac-b466e93509bc)
![image](https://github.com/user-attachments/assets/99337d1b-d554-48c9-8935-4c143848260d)

The extra opacity makes textures more visible, which gives more of an impression of a living organism as opposed to organelles wrapped in a bubble. When these bacteria were moving around on my screen, it felt significantly more like they were real 3D micro-organisms instead of abstract 2D representations. I think that the middle of the membrane being more opaque goes a long way towards making it feel like the membrane wraps all the way around the organism, and not just a circle containing your organism.

2024-10-25 08:14 UTC, hhyyrylainen approved these changes

2024-10-25 08:22 UTC, merged